#!/bin/bash
sleep 1
feh --bg-scale ~/Pictures/LIC.jpg&

xsetroot -cursor_name left_ptr&
trayer --edge top --align center --widthtype pixel --width 100 --SetDockType false --SetPartialStrut false  --transparent true --alpha 0 --tint 0x424242 --expand false --heighttype pixel --height 8 &
nm-applet&
#synergys

eject -i 1&
